/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("multi.java-application-conventions")
    id("multi.java-library-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("multi.app.App")
}
