/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("multi.java-application-conventions")
    id("multi.java-library-conventions")
}

dependencies {
    api(project(":list"))
}
