/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("multi.java-application-conventions")
    id("multi.java-library-conventions")
}

extra["hasTests"] = true

tasks.register("ok")

tasks.register("broken") {
    dependsOn("ok")
    doLast {
        throw RuntimeException("broken")
    }
}

gradle.taskGraph.beforeTask {
    println("executing $this ...")
}

gradle.taskGraph.afterTask {
    if (state.failure != null) {
        println("FAILED")
    } else {
        println("done")
    }
}